-- MySQL Script generated by MySQL Workbench
-- mié 05 may 2021 01:58:57
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Museo_Ibero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Museo_Ibero` (
  `CIF` VARCHAR(9) NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Direccion` VARCHAR(45) NULL,
  `Aforo` VARCHAR(45) NULL,
  PRIMARY KEY (`CIF`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Empleado` (
  `DNI_Empleado` VARCHAR(9) NOT NULL,
  `N_Seg_Social` VARCHAR(45) NULL,
  `Nombre` VARCHAR(45) NULL,
  `Apellido` VARCHAR(45) NULL,
  `Salario` FLOAT NULL,
  `Museo_Ibero_CIF` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`DNI_Empleado`),
  INDEX `fk_Empleado_Museo_Ibero_idx` (`Museo_Ibero_CIF` ASC) VISIBLE,
  CONSTRAINT `fk_Empleado_Museo_Ibero`
    FOREIGN KEY (`Museo_Ibero_CIF`)
    REFERENCES `mydb`.`Museo_Ibero` (`CIF`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Director`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Director` (
  `Experiencia` VARCHAR(200) NULL,
  `Empleado_DNI_Empleado` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`Empleado_DNI_Empleado`),
  CONSTRAINT `fk_Director_Empleado1`
    FOREIGN KEY (`Empleado_DNI_Empleado`)
    REFERENCES `mydb`.`Empleado` (`DNI_Empleado`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Guia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Guia` (
  `Idioma` VARCHAR(200) NULL,
  `Empleado_DNI_Empleado` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`Empleado_DNI_Empleado`),
  CONSTRAINT `fk_Guia_Empleado1`
    FOREIGN KEY (`Empleado_DNI_Empleado`)
    REFERENCES `mydb`.`Empleado` (`DNI_Empleado`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Guarda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Guarda` (
  `Turno` VARCHAR(10) NULL,
  `Empleado_DNI_Empleado` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`Empleado_DNI_Empleado`),
  CONSTRAINT `fk_Guarda_Empleado1`
    FOREIGN KEY (`Empleado_DNI_Empleado`)
    REFERENCES `mydb`.`Empleado` (`DNI_Empleado`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Limpiador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Limpiador` (
  `Zona_Museo` VARCHAR(50) NULL,
  `Empleado_DNI_Empleado` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`Empleado_DNI_Empleado`),
  CONSTRAINT `fk_Limpiador_Empleado1`
    FOREIGN KEY (`Empleado_DNI_Empleado`)
    REFERENCES `mydb`.`Empleado` (`DNI_Empleado`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Actividades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Actividades` (
  `Nombre` VARCHAR(60) NOT NULL,
  `Fecha` DATE NULL,
  `Tipo` VARCHAR(45) NULL,
  `Museo_Ibero_CIF` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`Nombre`, `Museo_Ibero_CIF`),
  INDEX `fk_Actividades_Museo_Ibero1_idx` (`Museo_Ibero_CIF` ASC) VISIBLE,
  CONSTRAINT `fk_Actividades_Museo_Ibero1`
    FOREIGN KEY (`Museo_Ibero_CIF`)
    REFERENCES `mydb`.`Museo_Ibero` (`CIF`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Exposicion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Exposicion` (
  `Cod_Exposicion` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Descripcion` VARCHAR(45) NULL,
  `Exposicioncol` DATE NULL,
  `Museo_Ibero_CIF` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`Cod_Exposicion`),
  INDEX `fk_Exposicion_Museo_Ibero1_idx` (`Museo_Ibero_CIF` ASC) VISIBLE,
  CONSTRAINT `fk_Exposicion_Museo_Ibero1`
    FOREIGN KEY (`Museo_Ibero_CIF`)
    REFERENCES `mydb`.`Museo_Ibero` (`CIF`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Sala`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Sala` (
  `N_Sala` INT NOT NULL,
  `Aforo` INT NULL,
  `Museo_Ibero_CIF` VARCHAR(9) NOT NULL,
  `Exposicion_Cod_Exposicion` INT NOT NULL,
  PRIMARY KEY (`N_Sala`, `Exposicion_Cod_Exposicion`),
  INDEX `fk_Sala_Museo_Ibero1_idx` (`Museo_Ibero_CIF` ASC) VISIBLE,
  INDEX `fk_Sala_Exposicion1_idx` (`Exposicion_Cod_Exposicion` ASC) VISIBLE,
  CONSTRAINT `fk_Sala_Museo_Ibero1`
    FOREIGN KEY (`Museo_Ibero_CIF`)
    REFERENCES `mydb`.`Museo_Ibero` (`CIF`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Sala_Exposicion1`
    FOREIGN KEY (`Exposicion_Cod_Exposicion`)
    REFERENCES `mydb`.`Exposicion` (`Cod_Exposicion`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Exposicion_has_Sala`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Exposicion_has_Sala` (
  `Exposicion_Cod_Exposicion` INT NOT NULL,
  `Sala_N_Sala` INT NOT NULL,
  PRIMARY KEY (`Exposicion_Cod_Exposicion`, `Sala_N_Sala`),
  INDEX `fk_Exposicion_has_Sala_Sala1_idx` (`Sala_N_Sala` ASC) VISIBLE,
  INDEX `fk_Exposicion_has_Sala_Exposicion1_idx` (`Exposicion_Cod_Exposicion` ASC) VISIBLE,
  CONSTRAINT `fk_Exposicion_has_Sala_Exposicion1`
    FOREIGN KEY (`Exposicion_Cod_Exposicion`)
    REFERENCES `mydb`.`Exposicion` (`Cod_Exposicion`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Exposicion_has_Sala_Sala1`
    FOREIGN KEY (`Sala_N_Sala`)
    REFERENCES `mydb`.`Sala` (`N_Sala`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Arte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Arte` (
  `Estilo` VARCHAR(45) NULL,
  `Exposicion_Cod_Exposicion` INT NOT NULL,
  PRIMARY KEY (`Exposicion_Cod_Exposicion`),
  CONSTRAINT `fk_Arte_Exposicion1`
    FOREIGN KEY (`Exposicion_Cod_Exposicion`)
    REFERENCES `mydb`.`Exposicion` (`Cod_Exposicion`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Historia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Historia` (
  `Epoca` VARCHAR(45) NULL,
  `Exposicion_Cod_Exposicion` INT NOT NULL,
  PRIMARY KEY (`Exposicion_Cod_Exposicion`),
  CONSTRAINT `fk_Historia_Exposicion1`
    FOREIGN KEY (`Exposicion_Cod_Exposicion`)
    REFERENCES `mydb`.`Exposicion` (`Cod_Exposicion`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Religion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Religion` (
  `Deidades` VARCHAR(45) NULL,
  `Exposicion_Cod_Exposicion` INT NOT NULL,
  PRIMARY KEY (`Exposicion_Cod_Exposicion`),
  CONSTRAINT `fk_Religion_Exposicion1`
    FOREIGN KEY (`Exposicion_Cod_Exposicion`)
    REFERENCES `mydb`.`Exposicion` (`Cod_Exposicion`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Antiguedades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Antiguedades` (
  `Tipo` VARCHAR(45) NULL,
  `Exposicion_Cod_Exposicion` INT NOT NULL,
  PRIMARY KEY (`Exposicion_Cod_Exposicion`),
  CONSTRAINT `fk_Antiguedades_Exposicion1`
    FOREIGN KEY (`Exposicion_Cod_Exposicion`)
    REFERENCES `mydb`.`Exposicion` (`Cod_Exposicion`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
